// Onchain API error codes
export const ERROR_CODES = {
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  UNSUPPORTED_CHAIN: 'UNSUPPORTED_CHAIN',
  MISSING_PARAMETER: 'MISSING_PARAMETER',
  RPC_ERROR: 'RPC_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
} as const;

